FROM dockerhub.tax.service.gov.uk/seleniarm/node-chromium:4.16.1-20231230

ARG TARGET_IP
ENV TARGET_IP $TARGET_IP

ARG TARGET_PORTS
ENV TARGET_PORTS $TARGET_PORTS

USER root

RUN apt-get -y update && \
  apt-get -y install rinetd dnsutils

COPY --chown=seluser:seluser run-rinetd.sh /opt/bin/run-rinetd.sh

RUN sudo chmod 755 /opt/bin/run-rinetd.sh

USER seluser

ENTRYPOINT ["/bin/bash", "/opt/bin/run-rinetd.sh"]
